#ifndef SYSCALL_H
#define SYSCALL_H

#define SYSCALL_WRITE 0
#define SYSCALL_EXIT 1
#define SYSCALL_YIELD 2
#define SYSCALL_GET_TIME 3
#define SYSCALL_FORK 4
#define SYSCALL_WAITPID 5
#define SYSCALL_EXEC 6
#define SYSCALL_READ 7
#define SYSCALL_GETS 8
#define SYSCALL_PIPE 9
#define SYSCALL_GETPID 10
#define SYSCALL_CLOSE 11
#define SYSCALL_OPEN 12

#endif
